### ISSUE TITLE
[Feature] Request for documentation / information about galera recovery and livenessProbes

### ISSUE THREAD

**Issue by anfechtung** [mariadb-operator/mariadb-operator#219]
I am looking for documentation or information on how the galera recovery timeouts will interact with livenessProbe and readinessProbe timeouts:

```
    galera:
      recovery:
        clusterBootstrapTimeout: 20m0s
        clusterHealthyTimeout: 20m0s
        enabled: true
        podRecoveryTimeout: 15m0s
        podSyncTimeout: 10m0s
```

```
    livenessProbe:
      failureThreshold: 30
      initialDelaySeconds: 60
      periodSeconds: 30
    readinessProbe:
      failureThreshold: 30
      initialDelaySeconds: 60
      periodSeconds: 30
```

Essentially, I would like to know which should be set for longer?  I have seen situations where my galera cluster has the livenessProbe fail, the pod is restarted, and then the pod never comes back up, failing to fully recover.

Should the recovery timeouts be less than the livenessProbe and readinessProbe overall timeouts, or longer than?  

What is the cluster and pod timeouts in the recovery section, and how should those be tuned?

Thanks.

**Comment by mmontes11** [comment]
Hey there! 

As described in the [Galera docs](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#api-reference), the best way to interact with documentation is `kubectl explain`:

>  What is the cluster and pod timeouts in the recovery section, and how should those be tuned?
```bash
kubectl explain mariadb.spec.galera.recovery

KIND:     MariaDB
VERSION:  mariadb.mmontes.io/v1alpha1

RESOURCE: recovery <Object>

DESCRIPTION:
     GaleraRecovery is the recovery process performed by the operator whenever
     the Galera cluster is not healthy. More info:
     https://galeracluster.com/library/documentation/crash-recovery.html.

FIELDS:
   clusterBootstrapTimeout      <string>
     ClusterBootstrapTimeout is the time limit for bootstrapping a cluster. Once
     this timeout is reached, the Galera recovery state is reset and a new
     cluster bootstrap will be attempted.

   clusterHealthyTimeout        <string>
     ClusterHealthyTimeout represents the duration at which a Galera cluster,
     that consistently failed health checks, is considered unhealthy, and
     consequently the Galera recovery process will be initiated by the operator.

   enabled      <boolean>
     Enabled is a flag to enable GaleraRecovery.

   podRecoveryTimeout   <string>
     PodRecoveryTimeout is the time limit for executing the recovery sequence
     within a Pod. This process includes enabling the recovery mode in the
     Galera configuration file, restarting the Pod and retrieving the sequence
     from a log file.

   podSyncTimeout       <string>
     PodSyncTimeout is the time limit we give to a Pod to reach the Sync state.
     Once this timeout is reached, the Pod is restarted.
```

> Essentially, I would like to know which should be set for longer?
> Should the recovery timeouts be less than the livenessProbe and readinessProbe overall timeouts, or longer than?

`spec.podRecoveryTimeout` and `spec.podSyncTimeout` should be longer than the liveness thresholds. We want Kubernetes to restart the `Pods` if something goes wrong, by doing so we might recover the cluster. If this doesn't help, maybe because the liveness probe check does not fail in certain situation, `mariadb-operator` will kick in and restart the `Pod` to help recovering the cluster.

> the pod never comes back up, failing to fully recover.

Could you provide the following to further investigate this?
- `Pod` logs
- `MariaDB` events:
```bash
kubectl get events --context kind-mdb --namespace mariadb --field-selector involvedObject.name=mariadb 
```

**Comment by anfechtung** [comment]
I was trying to redeploy to recreate the error, but now I have the operator stuck in a crash loop:

```
mariadb-mariadb-operator-7cbf4b5ddf-bvmmt                        0/1     CrashLoopBackOff   12 (4m56s ago)   44m
```

with the following error in the logs:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14bf858]

goroutine 762 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x16ead40, 0x2775f30})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildGaleraAgentContainer.func1(0xc0000f6700?, 0x0?, 0xc0007a9090)
        /app/pkg/builder/statefulset_container_builder.go:57 +0x518
github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildGaleraAgentContainer(_, _)
        /app/pkg/builder/statefulset_container_builder.go:67 +0x23f
github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildStsContainers(0x40d2ad?, 0xc0000f6700, 0x0)
        /app/pkg/builder/statefulset_container_builder.go:27 +0x36a
github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).buildStsPodTemplate(0x16dbdc0?, 0xc0000f6700, 0x18f5163?, 0x1a?)
        /app/pkg/builder/statefulset_builder.go:102 +0x3e
github.com/mariadb-operator/mariadb-operator/pkg/builder.(*Builder).BuildStatefulSet(0xc0007a9090, 0xc0000f6700, {{0xc0002f1c86?, 0xc0017f61c0?}, {0xc0002f1c90?, 0xc000093d40?}}, 0xc001b497a0?)
        /app/pkg/builder/statefulset_builder.go:75 +0x4ba
github.com/mariadb-operator/mariadb-operator/controllers.(*MariaDBReconciler).reconcileStatefulSet(0xc00015e4d0, {0x1b403f0, 0xc0027cf170}, 0xc0000f6700)
        /app/controllers/mariadb_controller.go:231 +0x149
github.com/mariadb-operator/mariadb-operator/controllers.(*MariaDBReconciler).Reconcile(0xc00015e4d0, {0x1b403f0, 0xc0027cf170}, {{{0xc000a2c310?, 0x0?}, {0xc000a2c330?, 0x40de67?}}})
        /app/controllers/mariadb_controller.go:155 +0x632
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b40348?, {0x1b403f0?, 0xc0027cf170?}, {{{0xc000a2c310?, 0x1817320?}, {0xc000a2c330?, 0x1b2ee98?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001a2820, {0x1b40348, 0xc0002b3b30}, {0x1746340?, 0xc0004300e0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320 +0x327
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001a2820, {0x1b40348, 0xc0002b3b30})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:230 +0x587
```

**Comment by anfechtung** [comment]
Regarding the timeouts, if `spec.podSyncTimeout` is longer than the liveness threshold *and* the sync process takes longer than the liveness threshold, won't k8s terminate the pod before pod synchronization is complete?  That could lead to an endless cycle where a pod in the mariadb cluster never becomes ready because it can never fully sync.

**Comment by anfechtung** [comment]
I reverted to a previous deployment.  The operator is no longer crashing, however the cluster is failing to come up:

```
mariadb-galera-0                                                 1/2     CrashLoopBackOff        2 (12s ago)     17m
mariadb-galera-1                                                 1/2     Running                 1 (2m48s ago)   17m
mariadb-galera-2                                                 0/2     Init:0/1                0               17m
mariadb-mariadb-operator-7cbf4b5ddf-mztlq                        1/1     Running                 0               21m
mariadb-mariadb-operator-webhook-79b6b887c8-vbb68                1/1     Running                 0               21m
```

The mariadb manifest:

```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  annotations:
    meta.helm.sh/release-name: mariadb
    meta.helm.sh/release-namespace: frostbite
  creationTimestamp: "2023-09-07T20:47:52Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: mariadb-1.0.0_466021b21e1e
    helm.toolkit.fluxcd.io/name: mariadb
    helm.toolkit.fluxcd.io/namespace: frostbite
  name: mariadb-galera
  namespace: frostbite
  resourceVersion: "38741"
  uid: 4b1db2b3-badc-496f-8454-6e12d3ff47b6
spec:
  galera:
    agent:
      gracefulShutdownTimeout: 5s
      image:
        pullPolicy: IfNotPresent
        repository: ghcr.io/mariadb-operator/agent
        tag: v0.0.2
      kubernetesAuth:
        enabled: true
      port: 5555
    enabled: true
    initContainer:
      image:
        pullPolicy: IfNotPresent
        repository: ghcr.io/mariadb-operator/init
        tag: v0.0.5
    recovery:
      clusterBootstrapTimeout: 10m0s
      clusterHealthyTimeout: 10m0s
      enabled: true
      podRecoveryTimeout: 20m0s
      podSyncTimeout: 10m0s
    replicaThreads: 1
    sst: mariabackup
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Mi
  image:
    pullPolicy: IfNotPresent
    repository: mariadb
    tag: 11.0.2
  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 180
  myCnf: "[mariadb]\nbind-address=0.0.0.0\ndefault_storage_engine=InnoDB\nbinlog_format=row\ninnodb_autoinc_lock_mode=2\nmax_allowed_packet=256M\nwsrep_provider_options=\"gcache.size
    = 1G\"       \n"
  myCnfConfigMapKeyRef:
    key: my.cnf
    name: config-mariadb-galera
  podSecurityContext:
    runAsUser: 0
  port: 3306
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 300
  replicas: 3
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  securityContext:
    seccompProfile:
      type: Unconfined
  service:
    annotations:
      kube-vip.io/loadbalancerIPs: 10.1.5.132
    type: LoadBalancer
  volumeClaimTemplate:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1500Mi
status:
  conditions:
  - lastTransitionTime: "2023-09-07T20:48:29Z"
    message: Not ready
    reason: StatefulSetNotReady
    status: "False"
    type: Ready
  currentPrimary: All
```

mariadb-galera-0 previous logs:

```
2023-09-07 21:15:02+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-09-07 21:15:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-09-07 21:15:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-09-07 21:15:04+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2023-09-07 21:15:04 0 [Note] Starting MariaDB 11.0.2-MariaDB-1:11.0.2+maria~ubu2204 source revision 0005f2f06c8e1aea4915887decad67885108a929 as process 1
2023-09-07 21:15:04 0 [Note] WSREP: Loading provider /usr/lib/galera/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
2023-09-07 21:15:04 0 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib/galera/libgalera_smm.so'
2023-09-07 21:15:04 0 [Note] WSREP: wsrep_load(): Galera 26.4.14(r06a0c285) by Codership Oy <info@codership.com> loaded successfully.
2023-09-07 21:15:04 0 [Note] WSREP: Initializing allowlist service v1
2023-09-07 21:15:04 0 [Note] WSREP: Initializing event service v1
2023-09-07 21:15:04 0 [Note] WSREP: CRC-32C: using 64-bit x86 acceleration.
2023-09-07 21:15:04 0 [Note] WSREP: Found saved state: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04:-1, safe_to_bootstrap: 0
2023-09-07 21:15:04 0 [Note] WSREP: GCache DEBUG: opened preamble:
Version: 2
UUID: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04
Seqno: 1 - 5
Offset: 1280
Synced: 1
2023-09-07 21:15:04 0 [Note] WSREP: Recovering GCache ring buffer: version: 2, UUID: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04, offset: 1280
2023-09-07 21:15:04 0 [Note] WSREP: GCache::RingBuffer initial scan...  0.0% (         0/1073741848 bytes) complete.
2023-09-07 21:15:04 0 [Note] WSREP: GCache::RingBuffer initial scan...100.0% (1073741848/1073741848 bytes) complete.
2023-09-07 21:15:04 0 [Note] WSREP: Recovering GCache ring buffer: found gapless sequence 1-5
2023-09-07 21:15:04 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...  0.0% (   0/1752 bytes) complete.
2023-09-07 21:15:04 0 [Note] WSREP: Recovering GCache ring buffer: found 2/7 locked buffers
2023-09-07 21:15:04 0 [Note] WSREP: Recovering GCache ring buffer: free space: 1073740432/1073741824
2023-09-07 21:15:04 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...100.0% (1752/1752 bytes) complete.
2023-09-07 21:15:04 0 [Note] WSREP: Passing config to GCS: base_dir = /var/lib/mysql/; base_host = mariadb-galera-0.mariadb-galera-internal.frostbite.svc.cluster.local; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /var/lib/mysql/; gcache.keep_pages_size = 0; gcache.keep_plaintext_size = 128M; gcache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 1G; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.fc_single_primary = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_
2023-09-07 21:15:04 0 [Note] WSREP: Start replication
2023-09-07 21:15:04 0 [Note] WSREP: Connecting with bootstrap option: 1
2023-09-07 21:15:04 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2023-09-07 21:15:04 0 [ERROR] WSREP: It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates. To force cluster bootstrap with this node, edit the grastate.dat file manually and set safe_to_bootstrap to 1 .
2023-09-07 21:15:04 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-0.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-1.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-2.mariadb-galera-internal.frostbite.svc.cluster.local) failed: 7
2023-09-07 21:15:04 0 [ERROR] Aborting
```

mariadb-galera-1 previous logs:

```
2023-09-07 21:15:35+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-09-07 21:15:35+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-09-07 21:15:36+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-09-07 21:15:37 0 [Note] Starting MariaDB 11.0.2-MariaDB-1:11.0.2+maria~ubu2204 source revision 0005f2f06c8e1aea4915887decad67885108a9
29 as process 1
2023-09-07 21:15:37 0 [Note] WSREP: Loading provider /usr/lib/galera/libgalera_smm.so initial position: 00000000-0000-0000-0000-0000000000
00:-1
2023-09-07 21:15:37 0 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib/galera/libgalera_smm.so'
2023-09-07 21:15:37 0 [Note] WSREP: wsrep_load(): Galera 26.4.14(r06a0c285) by Codership Oy <info@codership.com> loaded successfully.
2023-09-07 21:15:37 0 [Note] WSREP: Initializing allowlist service v1
2023-09-07 21:15:37 0 [Note] WSREP: Initializing event service v1
2023-09-07 21:15:37 0 [Note] WSREP: CRC-32C: using 64-bit x86 acceleration.
2023-09-07 21:15:37+00:00 [Note] [Entrypoint]: MariaDB upgrade information missing, assuming required
2023-09-07 21:15:37+00:00 [Note] [Entrypoint]: MariaDB upgrade (mariadb-upgrade) required, but skipped due to $MARIADB_AUTO_UPGRADE settin
g
2023-09-07 21:15:37 0 [Note] WSREP: Found saved state: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04:-1, safe_to_bootstrap: 1
2023-09-07 21:15:37 0 [Note] WSREP: GCache DEBUG: opened preamble:
Version: 2
UUID: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04
Seqno: 3 - 6
Offset: 2000
Synced: 1
2023-09-07 21:15:37 0 [Note] WSREP: Recovering GCache ring buffer: version: 2, UUID: 0bb0525f-4dc1-11ee-9c23-9fe33fed9a04, offset: 2000
2023-09-07 21:15:37 0 [Note] WSREP: GCache::RingBuffer initial scan...  0.0% (         0/1073741848 bytes) complete.
2023-09-07 21:15:37 0 [Note] WSREP: GCache::RingBuffer initial scan...100.0% (1073741848/1073741848 bytes) complete.
2023-09-07 21:15:37 0 [Note] WSREP: Recovering GCache ring buffer: found gapless sequence 3-6
2023-09-07 21:15:37 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...  0.0% (   0/1824 bytes) complete.
2023-09-07 21:15:37 0 [Note] WSREP: Recovering GCache ring buffer: found 2/6 locked buffers
2023-09-07 21:15:37 0 [Note] WSREP: Recovering GCache ring buffer: free space: 1073740656/1073741824
2023-09-07 21:15:37 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...100.0% (1824/1824 bytes) complete.
2023-09-07 21:15:37 0 [Note] WSREP: Passing config to GCS: base_dir = /var/lib/mysql/; base_host = mariadb-galera-1.mariadb-galera-interna
l.frostbite.svc.cluster.local; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.de
lay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_per
iod = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_w
indow = 2; evs.view_forget_timeout = PT24H; gcache.dir = /var/lib/mysql/; gcache.keep_pages_size = 0; gcache.keep_plaintext_size = 128M; g
cache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 1G; gcomm.thread_prio = ; gcs
.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.fc_single_primary = no; gcs.max_packet_size = 64500; 
gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_
2023-09-07 21:15:37 0 [Note] WSREP: Start replication
2023-09-07 21:15:37 0 [Note] WSREP: Connecting with bootstrap option: 0
2023-09-07 21:15:37 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2023-09-07 21:15:37 0 [Note] WSREP: Using CRC-32C for message checksums.
2023-09-07 21:15:37 0 [Note] WSREP: backend: asio
2023-09-07 21:15:37 0 [Note] WSREP: gcomm thread scheduling priority set to other:0 
2023-09-07 21:15:37 0 [Note] WSREP: access file(/var/lib/mysql//gvwstate.dat) failed(No such file or directory)
2023-09-07 21:15:37 0 [Note] WSREP: restore pc from disk failed
2023-09-07 21:15:37 0 [Note] WSREP: GMCast version 0
2023-09-07 21:15:37 0 [Note] WSREP: (b0b79bad-8222, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2023-09-07 21:15:37 0 [Note] WSREP: (b0b79bad-8222, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2023-09-07 21:15:37 0 [Note] WSREP: EVS version 1
2023-09-07 21:15:37 0 [Note] WSREP: gcomm: connecting to group 'mariadb-operator', peer 'mariadb-galera-0.mariadb-galera-internal.frostbite.svc.cluster.local:,mariadb-galera-1.mariadb-galera-internal.frostbite.svc.cluster.local:,mariadb-galera-2.mariadb-galera-internal.frostbite.svc.cluster.local:'
2023-09-07 21:15:37 0 [Note] WSREP: (b0b79bad-8222, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://10.66.187.145:4567
2023-09-07 21:15:40 0 [Note] WSREP: EVS version upgrade 0 -> 1
2023-09-07 21:15:40 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2023-09-07 21:15:40 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
2023-09-07 21:15:40 0 [Note] WSREP: view(view_id(NON_PRIM,b0b79bad-8222,1) memb {
        b0b79bad-8222,0
} joined {
} left {
} partitioned {
})
2023-09-07 21:15:40 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.58045S), skipping check
2023-09-07 21:16:10 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2023-09-07 21:16:10 0 [Note] WSREP: view((empty))
2023-09-07 21:16:10 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
         at ./gcomm/src/pc.cpp:connect():160
2023-09-07 21:16:10 0 [ERROR] WSREP: ./gcs/src/gcs_core.cpp:gcs_core_open():221: Failed to open backend connection: -110 (Connection timed out)
2023-09-07 21:16:11 0 [ERROR] WSREP: ./gcs/src/gcs.cpp:gcs_open():1669: Failed to open channel 'mariadb-operator' at 'gcomm://mariadb-galera-0.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-1.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-2.mariadb-galera-internal.frostbite.svc.cluster.local': -110 (Connection timed out)
2023-09-07 21:16:11 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2023-09-07 21:16:11 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-0.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-1.mariadb-galera-internal.frostbite.svc.cluster.local,mariadb-galera-2.mariadb-galera-internal.frostbite.svc.cluster.local) failed: 7
2023-09-07 21:16:11 0 [ERROR] Aborting
```

Based on the events you can see that the liveness probe is failing, and the container is restarted:

```
  Normal   Created                 28m                   kubelet                  Created container agent
  Normal   Started                 28m                   kubelet                  Started container agent
  Warning  Unhealthy               22m (x6 over 23m)     kubelet                  Readiness probe failed: command "bash -c mariadb -u root -p\"${MARIADB_ROOT_PASSWORD}\" -e \"SHOW STATUS LIKE 'wsrep_ready'\" | grep -c ON" timed out
  Warning  Unhealthy               15m (x25 over 25m)    kubelet                  Liveness probe failed: command "bash -c mariadb -u root -p\"${MARIADB_ROOT_PASSWORD}\" -e \"SHOW STATUS LIKE 'wsrep_ready'\" | grep -c ON" timed out
  Normal   Pulled                  10m (x6 over 21m)     kubelet                  Container image "mariadb:11.0.2" already present on machine
  Warning  BackOff                 4m57s (x39 over 12m)  kubelet                  Back-off restarting failed container
```

**Comment by mmontes11** [comment]
> Regarding the timeouts, if spec.podSyncTimeout is longer than the liveness threshold and the sync process takes longer than the liveness threshold, won't k8s terminate the pod before pod synchronization is complete? That could lead to an endless cycle where a pod in the mariadb cluster never becomes ready because it can never fully sync.

If the `livenessProbe` fails multiple times, the `Pod` will eventually enter in `CrashLoopBackoff`, meaning that the restarts will take exponentially longer, this time is not considered when it comes to tune up the `livenessProbe` thresholds. However, it means that in a `CrashLoopBackoff` situation, the cluster will take longer to recover, which is when the operator kicks in by killing the `Pod` after `spec.podSyncTimeout` is reached. Does this make sense?

**Comment by mmontes11** [comment]
> I reverted to a previous deployment. The operator is no longer crashing, however the cluster is failing to come up:

You have created a new `MariaDB`, are you also using the previous PVCs? If that is the case, could you also delete them so you start from a fresh cluster? This could imply that Galera attempts to connect to previous nodes, that no longer exist

**Comment by anfechtung** [comment]
This is a completely new cluster.  New MariaDB, new PVCs.

**Comment by kvaps** [comment]
Hi, I have the same issue, after restarting all the pods in one time

**Comment by kvaps** [comment]
> You have created a new MariaDB, are you also using the previous PVCs

How to recover from previous PVCs?

**Comment by kvaps** [comment]
Okay I fixed it by two commands:

```
kubectl exec my-db-1 -ti -- sh -c "printf '%s\n' '[galera]' 'wsrep_new_cluster=\"ON\"' > /etc/mysql/mariadb.conf.d/1-bootstrap.cnf"
kubectl exec my-db-1 -ti -- sed -i 's/safe_to_bootstrap: 0/safe_to_bootstrap: 1/' /var/lib/mysql/grastate.dat
```

**Comment by comminutus** [comment]
I also ran into this issue where I need to be able to restore the cluster with previous PVCs/PVs.  The commands that @kvaps mentioned also worked for me in bringing my cluster back up.

Is there some way the operator can detect that the cluster needs to be re-initialized and issue similar commands?  It's fairly common for my use case to have the galera cluster disappear (node restarts, maintenance, etc) and have to restart from existing PVCs/PVs.

**Comment by tsgit** [comment]
I also ran into the problem with the livenessprobe crashing the pod before the recovery of a pod in a 3 node galera cluster was complete.

The manifest follows the example here
https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_galera_full.yaml#L70-L73
and here
https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_galera_full.yaml#L158-L166

The pod went into infinite crashloop (500+ cycles). The logs show that on each restart it initiates a sync, but doesn't get to completions.

I edited the mariadb resource and temporarily increase the initialDelaySeconds to 5 minutes.

This allowed the pod to successfully resync and join the cluster. 

I wonder if the operator could temporarily pause the liveness/health probes while recovery is ongoing?

**Comment by tsgit** [comment]
I believe an additional `startupProbe` like 
```
startupProbe:
  httpGet:
    path: /health
    port: 5555
  failureThreshold: 30
  periodSeconds: 10
```
would also work to delay the premature killing of the pod while it's still syncing.  it allows for 10*30=300s = 5m before the livenessProbe kicks in

**Comment by mmontes11** [comment]
> I wonder if the operator could temporarily pause the liveness/health probes while recovery is ongoing?

The agent container that controls the `/health` endpoint does return 200 OK during recovery:
- https://github.com/mariadb-operator/mariadb-operator/blob/1ba711991deb4119b9a6e900e261e9caa63d7c3c/pkg/galera/agent/handler/probe.go#L50

In the version to be released soon (`v0.0.30`) the liveness probe is paused, but not the readiness, to avoid sending traffic to not ready replicas during recovery. Please make sure to upgrade the `agent` container to a recent version, this will be actually  covered in the  `v0.0.30` upgrade guide:

```diff
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  ...
  galera:
    agent:
-      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.28
+      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.29
```

> I believe an additional startupProbe like

That would also work, but unfortunately `startupProbes` are not supported at the moment, will need to think about all the possible implications and when to pause them from the agent `/health` endpoint. As an alternative, as you said, you can add `initialDelaySeconds` to both the liveness and readiness probe, which should be a similar effect:

``` yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  storage:
    size: 1Gi

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5
```

Bear in mind that updating the probes requires a rolling upgrade, as the `Pod` template is changed.

**Comment by mmontes11** [comment]
Startup probes contributed by @vixns  in https://github.com/mariadb-operator/mariadb-operator/pull/1053. Will be released in `0.37.0`.

**Comment by mmontes11** [comment]
Startup probes support been released in [0.37.0](https://github.com/mariadb-operator/mariadb-operator/releases/tag/0.37.0) 🚀
