### ISSUE TITLE
[Bug] Operator crash - panic in reconciler: invalid memory

### ISSUE THREAD

**Issue by cloudnull** [mariadb-operator/mariadb-operator#491]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
Operator crash within the following error while deploying maxscale.

``` log
{"level":"info","ts":1711174285.86227,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"maxscale","controllerGroup":"k8s.mariadb.com","
controllerKind":"MaxScale","MaxScale":{"name":"maxscale-galera","namespace":"openstack"},"namespace":"openstack","name":"maxscale-galera","reconcileID":"bb4d009f-669f-44a3-8d44-5a0edecb5209"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x170142d]

goroutine 916 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x193a800?, 0x2cb8ac0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/mariadb-operator/mariadb-operator/controller.(*MaxScaleReconciler).reconcileAuth(0xc00029b170, {0x1e895f0, 0xc002e0f4d0}, 0xc00379a4c0?)
        /app/controller/maxscale_controller.go:612 +0xeed
github.com/mariadb-operator/mariadb-operator/controller.(*MaxScaleReconciler).Reconcile(0xc00029b170, {0x1e895f0, 0xc002e0f4d0}, {{{0xc004b9efa6?, 0x5?}, {0xc004b9efc0?, 0xc001fa5d48?}}})
        /app/controller/maxscale_controller.go:189 +0x91e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1e8d788?, {0x1e895f0?, 0xc002e0f4d0?}, {{{0xc004b9efa6?, 0xb?}, {0xc004b9efc0?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005c6780, {0x1e89628, 0xc0005beb40}, {0x19cddc0?, 0xc003afeee0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316 +0x3cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005c6780, {0x1e89628, 0xc0005beb40})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 137
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:223 +0x565
```

**Expected behaviour**
While the pod recovered, I would not have expected this crash.

**Environment details**:
- Kubernetes version: v1.28.6
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.27.0
- Install method: helm via kustomize
- Install flavor: custom

**Comment by mmontes11** [comment]
Thanks for reporting @cloudnull ! 

There was a race condition defaulting `spec.auth.syncMaxConnections` and derefering its pointer, causing a crash. It would only happen once, as it will most likely be defaulted in further reconciliation cycles. 

Fixed by https://github.com/mariadb-operator/mariadb-operator/pull/492, stay tunned for the next release!

**Comment by cloudnull** [comment]
Thanks @mmontes11 for the update.
