### ISSUE TITLE
[Bug] Creating an SQLJob with "unknown" dependency get the operator to crash

### ISSUE THREAD

**Issue by sennerholm** [mariadb-operator/mariadb-operator#577]
**Documentation**
- [x ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
<!--
If you create an SQLJob with mariadb operator ghcr.io/mariadb-operator/mariadb-operator:v0.0.27 you get it to crash with the following log:
```
{"level":"info","ts":1713790751.308197,"msg":"Dependency 'job-not-created' not found","controller":"sqljob","controllerGroup":"k8s.mariadb.com","controllerKind":"SqlJob","SqlJob":{"name":"with-with-wrong-dependency-058a94b62a","namespace":"bridge"},"namespace":"bridge","name":"with-with-wrong-dependency-058a94b62a","reconcileID":"e5375ccf-9a74-4e17-ad89-7fbec7b6baee"}
{"level":"info","ts":1713790751.3222082,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"sqljob","controllerGroup":"k8s.mariadb.com","controllerKind":"SqlJob","SqlJob":{"name":"with-with-wrong-dependency-058a94b62a","namespace":"bridge"},"namespace":"bridge","name":"with-with-wrong-dependency-058a94b62a","reconcileID":"e5375ccf-9a74-4e17-ad89-7fbec7b6baee"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x348 pc=0x1712c46]

goroutine 579 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x193a800?, 0x2cb8ac0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/mariadb-operator/mariadb-operator/api/v1alpha1.(*SqlJob).IsComplete(...)
	/app/api/v1alpha1/sqljob_types.go:103
github.com/mariadb-operator/mariadb-operator/controller.(*SqlJobReconciler).waitForDependencies(0xc0003f4d70, {0x1e895f0, 0xc000d95cb0}, 0xc000143180)
	/app/controller/sqljob_controller.go:132 +0x2e6
github.com/mariadb-operator/mariadb-operator/controller.(*SqlJobReconciler).Reconcile(0xc0003f4d70, {0x1e895f0, 0xc000d95cb0}, {{{0xc000afd826?, 0x5?}, {0xc000afeea0?, 0xc000cc5d48?}}})
	/app/controller/sqljob_controller.go:61 +0x1c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1e8d788?, {0x1e895f0?, 0xc000d95cb0?}, {{{0xc000afd826?, 0xb?}, {0xc000afeea0?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000122aa0, {0x1e89628, 0xc000416ff0}, {0x19cddc0?, 0xc000c57b00?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316 +0x3cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000122aa0, {0x1e89628, 0xc000416ff0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 132
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:223 +0x565```
for code blocks of your kubectl output or YAML files.
-->

**Expected behaviour**
<!--A concise description of what you expected to happen.-->
Not starting the SqlJob before the dependency exists and are OK. Not crashing

**Steps to reproduce the bug**
<!--Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.-->
Create a job like:

```
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: my-name
spec:
  restartPolicy: Never
  dependsOn:
    - name: not-existing-job
  mariaDbRef:
    name: mariadb
  username: root
  passwordSecretKeyRef:
    name: mariadb-root
    key: password
  database: my-db
  sql: "use db"
```

**Debug information**
I have added logs above, please let me know if you want anything more.

**Environment details**:
- Kubernetes version: 1.28.3
- mariadb-operator version: 0.0.27
- Install method: helm+argocd

**Additional context**
<!--Add any other context  here.-->

**Comment by mmontes11** [comment]
@sennerholm Thanks for reporting. This is pretty much what I need:
```bash
dependsOn:
    - name: not-existing-job
```
Thanks!

**Comment by am6737** [comment]
Hey @mmontes11 

Can you hand it over to me? I'm more than happy to

**Comment by mmontes11** [comment]
@am6737 sure, thanks for looking into it
